### ISSUE TITLE
dicom_type for CT?

### ISSUE THREAD

**Issue by dulicui742** [tomaroberts/nii2dcm#32]
Hello!
        when I run nii2dcm input.nii.gz output -d CT, I got :
<img width="907" alt="error" src="https://github.com/tomaroberts/nii2dcm/assets/77182160/011147cb-e5da-413b-ade2-28b13b4a731a">

<img width="516" alt="code" src="https://github.com/tomaroberts/nii2dcm/assets/77182160/a879d981-123b-4f4b-9b7a-b58cb5745a19">

dicom_type only for MR and SVR?

**Comment by tomaroberts** [comment]
Hi @dulicui742 – nii2dcm is only for MR DICOMs so far. The intention is to include CT DICOMs further down the line, or you are welcome to contribute if you want! Thanks.

**Comment by tomaroberts** [comment]
I've made the CLI a bit more explicit to convey currently available DICOM types: https://github.com/tomaroberts/nii2dcm/pull/33/commits/f985a4661eaac6ecb9e29ffa3649b1e67b30c998
